#!/bin/bash

source /kb/deployment/user-env.sh

SERVICE=awe_service
SERVICE_DIR=$KB_TOP/services/$SERVICE

if [ ! -f $SERVICE_DIR/service.pid ]; then
   echo "No pid file $SERVICE_DIR/service.pid found for service $SERVICE"
   exit
fi

PID=`cat $SERVICE_DIR/service.pid`
kill $PID 2>&1
rm $SERVICE_DIR/service.pid
